### ISSUE TITLE
getEvents function name confusing

### ISSUE THREAD

**Issue by bogdangi** [FanMilesGmbH/fanmiles-redis-helper#1]
When you have and method to `getEvents` usually it should not remove events.
Much better to use `popEvents` then it not so confused.

**Comment by mihaerzen** [comment]
I agree `getEvents` does not indicate removing of the events and we can find a better name. I don't really like the name `popEvents` as well because it indicates removing from the end however it actually removes only events up to the given timestamp. Meaning from the beginning. Maybe `retrieveAndRemove`? Any ideas?

**Comment by mihaerzen** [comment]
@bogdangi This issue was resolved with the latest pull request #2
